# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 23:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='image',
            field=models.ImageField(blank='True', upload_to='imagens', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='plataforma',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.plataforma'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
