# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_auto_20170426_2036'),
        ('solicitacao', '0002_auto_20170510_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='jogo',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='jogo_escolhido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogosolicitados', to='jogo.Jogo'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='jogo_solicitado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jogosolicitante', to='jogo.Jogo'),
            preserve_default=False,
        ),
    ]
